apiVersion: apps/v1
kind: Deployment
metadata:
  name: Budget_Calculator
  namespace: capstone
  labels:
    name: Budget_Calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: Budget_Calculator-pod
  strategy:
    type: Recreate
  template:
    metadata:
      name: Budget_Calculator-pod
      labels:
        name: Budget_Calculator-pod
    spec:
      containers:
        - name:  Budget_Calculator
          image: sweety1995/nodejs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: Budget_Calculator-service
  namespace: capstone
  labels:
    name: Budget_Calculator-service
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32001
  selector:
    name: Budget_Calculator-pod
  type: NodePort
